--- Makefile	2022-09-18 22:44:39.488943590 +0800
+++ Makefile	2022-09-18 22:44:39.488943590 +0800
@@ -22,6 +22,7 @@ DIR_UBOOT   = $(DIR_OSLAB)/u-boot
 HOST_CC         = gcc
 CROSS_PREFIX    = riscv64-unknown-linux-gnu-
 CC              = $(CROSS_PREFIX)gcc
+AR              = $(CROSS_PREFIX)ar
 OBJDUMP         = $(CROSS_PREFIX)objdump
 GDB             = $(CROSS_PREFIX)gdb
 QEMU            = $(DIR_QEMU)/riscv64-softmmu/qemu-system-riscv64
